#ifndef FFL_COORDINATE_TYPE_H_
#define FFL_COORDINATE_TYPE_H_

#ifdef __cplusplus
extern "C" {
#endif

typedef enum FFLCoordinateType
{
    FFL_COORDINATE_TYPE_X_PLUS  = 0x00000001, // CFL_COORDINATE_XP
    FFL_COORDINATE_TYPE_X_MINUS = 0x000000FF, // CFL_COORDINATE_XM
    FFL_COORDINATE_TYPE_Y_PLUS  = 0x00000100, // CFL_COORDINATE_YP
    FFL_COORDINATE_TYPE_Y_MINUS = 0x0000FF00, // CFL_COORDINATE_YM
    FFL_COORDINATE_TYPE_Z_PLUS  = 0x00010000, // CFL_COORDINATE_ZP
    FFL_COORDINATE_TYPE_Z_MINUS = 0x00FF0000, // CFL_COORDINATE_ZM

    FFL_COORDINATE_TYPE_DEFAULT_UP    = FFL_COORDINATE_TYPE_Y_PLUS,
    FFL_COORDINATE_TYPE_DEFAULT_FRONT = FFL_COORDINATE_TYPE_Z_PLUS,
}
FFLCoordinateType;

#ifdef __cplusplus
}
#endif

#endif // FFL_COORDINATE_TYPE_H_
